"""Inicial

Revision ID: 712a951f6a14
Revises: 
Create Date: 2021-04-27 10:04:58.902253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712a951f6a14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
