"""Add atributos Tamanho

Revision ID: 754f6250de28
Revises: c899dc5145fd
Create Date: 2021-04-27 08:02:42.937418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754f6250de28'
down_revision = 'c899dc5145fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('tamanhos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'tamanhos')
    # ### end Alembic commands ###
